### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Robert-W** [Robert-W/esri-react-toc#1]
### TODO
- [x] Create build scripts, should be a minified ES5 compatible AMD module so people can plug it in to their project after compilation
- [ ] Add Usage Documentation
- [ ] Make a better contributors guide
- [ ] Add Examples using `Map`, `WebMap`, and more.
- [ ] Add Examples demonstrating how all the props work.
- [ ] Add multiple examples of how to integrate the project 
- [ ] Clean up `src` folder.
  - Since it is under development, usage examples live in the src directory so I can work and test faster. These should be removed and placed in an `examples` directory and `src` should only contain the TOC source code when stable.
- [ ] Support more layer types (maybe more than just below).
  - [ ] Group Layers
  - [ ] Tile (Web and Vector as well) Layers
  - [ ] Graphics Layer
- [x] Test more against SceneViews
- [ ] Test against WebScene.
- [ ] Add more props, these are just ideas
  - [x] `separateSubLayers`: MapImageLayers that have sublayers would be shown as separate entries in the TOC so they could be manipulated individually, versus turning the whole layer on or off. Useful for `WebMap` type. 
  - [ ] `overrides`: Object whose key would be a layer id and value would be something to override:
    - [ ] `legendImg`: to use a simple `img` tag with the provided image for the legend instead of the endpoint
    - [ ] `legendUrl` & `legendId`: If your endpoint does not have a nice legend and you have another endpoint to use, provide that here.  If it's a specific sublayer, specify that as well otherwise the whole legend will be returned.
    - [ ] `label`: Override the layer name and add a custom name. Useful if you want to support other languages.
    - [ ] `sublabel`: Sublabel to show underneath the layer label. Useful for attribution or other things.
    - [ ] `children`: Custom react components to embed under the appropriate layer.  If you want to build some custom control, like a time slider that is layer specific, and have it embedded in the TOC, do so here.  The user should also be able to subscribe to change events via `layerDidUpdate` prop so they can show and hide custom controls that are not in the scope of the TOC widget.
